define({ 
    "hpc.queues": "tesla gpu tizard mecheng abraham short gtx3",

    "nova.domains": [{"id": 1, "name":"Flinders"}, 
                     {"id": 2, "name":"Adelaide"}, 
                     {"id": 3, "name":"UniSA"}], 
    "nova.availability.zone": "sa ",//SA Only
    
    "allocation.summary.invisible.filesystem": [
                     "commvault-test-sb", 
                     "ersa-backups", 
                     "ersa-ckan-dev", 
                     "ersa-ckan-test", 
                     "ersa-cloud-aptmirror", 
                     "ersa-drop", 
                     "ersa-mediafluxtest-mig", 
                     "ersa-mediafluxtest-nomigration", 
                     "ersa-storage-home", 
                     "ersa-tau", 
                     "test-data-intranet", 
                     "vmware-swing-lun", 
                     "ersa-vmfs-backup", 
                     "ersa-vmware-backup", 
                     "livearcdata", 
                     "ersa-ckan-prod-app", 
                     "ersa-ckan-prod-backup", 
                     "ersa-cml-earth", 
                     "ersa-cml-tizarddeploy",  
                     "SD_FS_01", 
                     "SD_FS_02"],
    
    "filesystem.blacklist": [
                    "/export/compellent/emu-torque_ha",
                    "/export/compellent/genomicsdb",
                    "/export/compellent/hpchome",
                    "/export/compellent/hpcmigrationarchive",
                    "/export/compellent/hpcoptshared",
                    "/export/compellent/hpcscratch",
                    "/export/compellent/hpctest",
                    "/export/compellent/tizarddeploy",
                    "SD_FS_01",
                    "SD_FS_02",
                    "commvault-test-sb",
                    "ersa-backups",
                    "ersa-ckan-dev",
                    "ersa-ckan-prod-app",
                    "ersa-ckan-prod-backup",
                    "ersa-ckan-test",
                    "ersa-cloud-aptmirror",
                    "ersa-cml-tizarddeploy",
                    "ersa-drop",
                    "ersa-mediafluxtest-mig",
                    "ersa-mediafluxtest-nomigration",
                    "ersa-owncloud_dev",
                    "ersa-sacgf-owncloud_pilot",
                    "ersa-storage-home",
                    "ersa-tau",
                    "ersa-vmfs-backup",
                    "ersa-vmware-backup",
                    "livearcdata",
                    "nfs-test",
                    "test-data-intranet",
                    "unisa",
                    "vmware-swing-lun"
    ]
});
